# Generated by Django 4.1.2 on 2023-02-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prace',
            new_name='price',
        ),
    ]
